name: Build Succeed PR

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Build the Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.turbo
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Install Turbo globally
        run: npm install -g turbo

      - name: Build @repo/ui package
        run: npx turbo run build --filter=@repo/ui
      
      - name: Build web package
        run: npx turbo run build --filter=web
      
      - name: Run Next.js build
        run: npm run build

      - name: Build packages using Turbo
        run: npx turbo run build --filter=web
